### PR TITLE
basic docusaurus setup

### PR DESCRIPTION
**Pull request by darshkpatel**

### CODE REVIEW

**Comment by darshkpatel** [comment]
> Is it conventional to have another nested `package.json` in this project? If it's fine then I think we can merge this into master.

https://vercel.com/guides/deploying-docusaurus-with-vercel
the vercel guide essentially makes this as a independent application. 
makes sense since we cannot deploy something on a subdomain / route directly , but can easily deploy a sub-directory using vercel 

I'll prolly setup nginx on a vps later

**Comment by chuabingquan** [comment]
@darshkpatel Looks good to me. Do you want to do the honours of merging this to master?

**Comment by darshkpatel** [comment]
haha sure

**Comment by darshkpatel** [comment]
Ref:  #2

**Pull request merged**
