### PR TITLE
Static Discover Page UI

### PR DESCRIPTION
**Pull request by chuabingquan**
This pull request intends to merge a static (hardcoded) version of the discover page into the `master` branch. From there, I can start working on integrations with our APIs.

### CODE REVIEW

**Comment by darshkpatel** [comment]
since the CI is not working https://cross-pods.darshkpatel.now.sh

**Comment by darshkpatel** [comment]
@chuabingquan There seem to be a conflict with the packages

**Comment by chuabingquan** [comment]
@darshkpatel Let me go and resolve it

**Comment by chuabingquan** [comment]
@darshkpatel I've resolved conflicts for `package.json`. I'd suggest that we don't touch the yarn lock file and regenerate a new one. What do you think?

**Comment by darshkpatel** [comment]
> @darshkpatel I've resolved conflicts for `package.json`. I'd suggest that we don't touch the yarn lock file and regenerate a new one. What do you think?

yup.

**Comment by chuabingquan** [comment]
@darshkpatel Alright, if there's no issue I'll proceed to merge into master.

**Pull request merged**
